---
apiVersion: v1
kind: Service
metadata:
  name: user-mongodb
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app-name: user-mongodb
spec:
  ports:
  - port: 27017
  selector:
    death-star-project: media-microsvc
    app-name: user-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mongodb
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app-name: user-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: media-microsvc
      app-name: user-mongodb
  template:
    metadata:
      labels: 
        death-star-project: media-microsvc
        app-name: user-mongodb
      name: user-mongodb
    spec:
      containers:
      - name: user-mongodb
        image: nicklin9907/erms:mongo
      restartPolicy: Always
