apiVersion: v1
kind: PersistentVolume
metadata:
  name: geo-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/volumes/geo-pv
    type: DirectoryOrCreate
  storageClassName: geo-storage
  volumeMode: Filesystem
