apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-reservation
  name: mongodb-reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-reservation
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-reservation
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k8s-bk-15
                - k8s-bk-16
                - k8s-bk-17
                - k8s-bk-18
      containers:
      - image: nicklin9907/erms:mongo
        imagePullPolicy: IfNotPresent
        name: hotel-reserv-reservation-mongo
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        volumeMounts:
        - mountPath: /data/db
          name: reservation
      hostname: reservation-db
      restartPolicy: Always
      volumes:
      - name: reservation
        persistentVolumeClaim:
          claimName: reservation-pvc
status: {}
