apiVersion: v1
kind: PersistentVolume
metadata:
  name: reservation-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/volumes/reservation-pv
    type: DirectoryOrCreate
  storageClassName: reservation-storage
  volumeMode: Filesystem
