apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/volumes/user-pv
    type: DirectoryOrCreate
  storageClassName: user-storage
  volumeMode: Filesystem
