apiVersion: apps/v1
kind: Deployment
metadata:
  name: memoryinterference
  labels:
    app: memoryinterference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memoryinterference
  template:
    metadata:
      labels:
        app: memoryinterference
        node: mynode
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - one
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
      - name: memoryinterference
        image: ibench:v0.3
        command: ["/ibench/src/memCap"]
        args: ["60s 2 2s"]
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"