---
apiVersion: v1
kind: Service
metadata:
  name: media-mongodb
  labels:
    death-star-project: social-network
    app-name: media-mongodb
  namespace: social-network
spec:
  ports:
  - port: 27017
  selector:
    death-star-project: social-network
    app-name: media-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-mongodb
  labels:
    death-star-project: social-network
    app-name: media-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app-name: media-mongodb
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app-name: media-mongodb
      name: media-mongodb
    spec:
      containers:
      - name: media-mongodb
        image: nicklin9907/erms:mongo
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
